name: Dispatch

on: [workflow_dispatch]

jobs:
  validate:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Write branch and commit info
      run: |
        branch=$(git rev-parse --abbrev-ref HEAD)
        hash=$(git rev-parse --short=8 HEAD)
        echo "$branch.$hash" > version.txt

    - name: Authorize Git
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"

    - name: Update Submodule
      run: |
        git submodule update  --init --recursive --remote -f
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Commit Changes
      run: |
        git commit -am "chore(submodule): Update Translation Version"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Validate JSON and YAML
      id: json-yaml-validate
      uses: GrantBirki/json-yaml-validate@v3
      with:
        use_gitignore: false

    - name: Validate Resource
      id: resource-validate
      run: python ./scripts/resource_validator.py ./local-files/resource

    - name: Send Notification to Discord
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Validate"

  dispatch:

    runs-on: ubuntu-latest

    needs: validate

    steps:
    - name: Dispatch Update Submodule to gakuen-imas-localify-zh-TW
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        repository: yotv2000tw/gakuen-imas-localify-zh-TW
        event-type: update-submodule

    - name: Send Notification to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "Dispatch"